/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mal;

import mal.step0_repl.Step0_REPL;

import java.util.Arrays;
import java.util.Scanner;
import java.util.function.Function;

public class App {
    public static String getGreeting() {
        return "Welcome to MAL.";
    }

    public static void main(String[] args) {
        startREPL();
    }

    private static void startREPL() {
        System.out.println(getGreeting());
        Scanner scanner = new Scanner(System.in);
        boolean running = true;
        while (running) {
            System.out.print("user> ");
            String line = scanner.nextLine();
            if (line.equals("exit")) {
                running = false;
            }
            System.out.println(Step0_REPL.rep(line));
        }
        System.out.println("Exiting.");
        scanner.close();
    }
}
