all:
	@echo "Building..."
	@./gradlew build

# match any input starting with step
step%:
	@echo "Building step: $@"
	@./gradlew build

clean:
	@echo "Cleaning..."
	@./gradlew clean

test:
	@echo "Running tests..."
	@./gradlew test
